database/rails_exa/p2/config/routes.rb
Rails.application.routes.draw do
  resources :puntos
  resources :points
  resources :pets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

database/rails_exa/p2/app/models/pet.rb
class Pet < ApplicationRecord
end

database/rails_exa/p2/app/models/point.rb
class Point < ApplicationRecord
end

database/rails_exa/p2/app/models/punto.rb
class Punto < ApplicationRecord
end

database/rails_exa/p2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

database/rails_exa/p2/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:type, :name)
    end
end

database/rails_exa/p2/app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:type, :name)
    end
end

database/rails_exa/p2/app/controllers/puntos_controller.rb
class PuntosController < ApplicationController
  before_action :set_punto, only: [:show, :edit, :update, :destroy]

  # GET /puntos
  # GET /puntos.json
  def index
    @puntos = Punto.all
  end

  # GET /puntos/1
  # GET /puntos/1.json
  def show
  end

  # GET /puntos/new
  def new
    @punto = Punto.new
  end

  # GET /puntos/1/edit
  def edit
  end

  # POST /puntos
  # POST /puntos.json
  def create
    @punto = Punto.new(punto_params)

    respond_to do |format|
      if @punto.save
        format.html { redirect_to @punto, notice: 'Punto was successfully created.' }
        format.json { render :show, status: :created, location: @punto }
      else
        format.html { render :new }
        format.json { render json: @punto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puntos/1
  # PATCH/PUT /puntos/1.json
  def update
    respond_to do |format|
      if @punto.update(punto_params)
        format.html { redirect_to @punto, notice: 'Punto was successfully updated.' }
        format.json { render :show, status: :ok, location: @punto }
      else
        format.html { render :edit }
        format.json { render json: @punto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puntos/1
  # DELETE /puntos/1.json
  def destroy
    @punto.destroy
    respond_to do |format|
      format.html { redirect_to puntos_url, notice: 'Punto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_punto
      @punto = Punto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def punto_params
      params.require(:punto).permit(:tipo, :nombre)
    end
end

database/rails_exa/p2/app/helpers/application_helper.rb
module ApplicationHelper
end

database/rails_exa/p2/app/helpers/pets_helper.rb
module PetsHelper
end

database/rails_exa/p2/app/helpers/points_helper.rb
module PointsHelper
end

database/rails_exa/p2/app/helpers/puntos_helper.rb
module PuntosHelper
end

database/rails_exa/p2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

database/rails_exa/p2/app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

database/rails_exa/p2/app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

database/rails_exa/p2/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.type %></td>
        <td><%= pet.name %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

database/rails_exa/p2/app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

database/rails_exa/p2/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @pet.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

database/rails_exa/p2/app/views/points/_form.html.erb
<%= form_with(model: point, local: true) do |form| %>
  <% if point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

database/rails_exa/p2/app/views/points/edit.html.erb
<h1>Editing Point</h1>

<%= render 'form', point: @point %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

database/rails_exa/p2/app/views/points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Points</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.type %></td>
        <td><%= point.name %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

database/rails_exa/p2/app/views/points/new.html.erb
<h1>New Point</h1>

<%= render 'form', point: @point %>

<%= link_to 'Back', points_path %>

database/rails_exa/p2/app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @point.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @point.name %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>

database/rails_exa/p2/app/views/puntos/_form.html.erb
<%= form_with(model: punto, local: true) do |form| %>
  <% if punto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(punto.errors.count, "error") %> prohibited this punto from being saved:</h2>

      <ul>
      <% punto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

database/rails_exa/p2/app/views/puntos/edit.html.erb
<h1>Editing Punto</h1>

<%= render 'form', punto: @punto %>

<%= link_to 'Show', @punto %> |
<%= link_to 'Back', puntos_path %>

database/rails_exa/p2/app/views/puntos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Puntos</h1>
<p>Registra puntos del mapa</p>

<hr>
<%= link_to 'New Punto', new_punto_path %>
<hr>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puntos.each do |punto| %>
      <tr>
        <td><%= punto.tipo %></td>
        <td><%= punto.nombre %></td>
        <td><%= link_to 'Show', punto %></td>
        <td><%= link_to 'Edit', edit_punto_path(punto) %></td>
        <td><%= link_to 'Destroy', punto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

database/rails_exa/p2/app/views/puntos/new.html.erb
<h1>New Punto</h1>

<%= render 'form', punto: @punto %>

<%= link_to 'Back', puntos_path %>

database/rails_exa/p2/app/views/puntos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @punto.tipo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @punto.nombre %>
</p>

<%= link_to 'Edit', edit_punto_path(@punto) %> |
<%= link_to 'Back', puntos_path %>